name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "."
          target: "/home/azureuser/proj/db-lab4"

      - name: Restart Flask app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /home/azureuser/proj/db-lab4/Db-4-laba
            pkill -f app.py || true
            nohup python3 app.py > app.log 2>&1 &
